<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_mobile">
  
  <!-- xacro properties -->
  <xacro:property name="chassis_length" value="0.8"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.25"/>
  <xacro:property name="wheel_height" value="0.05"/>
  <xacro:property name="wheel_radius" value="0.15"/>
  <xacro:property name="caster_radius" value="0.15"/>
  <xacro:property name="wheels_front_offset" value="0.25"/>
  <xacro:property name="caster_back_offset" value="0.25"/>
  <xacro:property name="chassis_mass" value="5.0"/>
  <xacro:property name="caster_mass" value="0.01"/>
  <xacro:property name="wheel_mass" value="1.0"/>
  
  <!-- materials -->
  <xacro:include filename="materials.xml"/>  
  
  <!-- gazebo properties -->
  <xacro:include filename="gazebo.xml"/>
  
  <!-- links -->
  <link name="chassis">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="grey"/>
    </visual>
    
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    
    <inertial>
      <mass value="${chassis_mass}"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="black"/>
    </visual>
    
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    
    <inertial>
      <mass value="${caster_mass}"/>
      <inertia ixx="1e-6" iyy="1e-6" izz="1e-6" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_height/2}"/>
      <material name="red"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_height/2}"/>
      <surface>
        <friction>
          <ode>
            <mu>100000</mu>
            <mu2>100000</mu2>
            <slip1>0</slip1>
            <slip2>0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-wheel_height/2}"/>
      <material name="red"/>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${-wheel_height/2}"/>
      <surface>
        <friction>
          <ode>
            <mu>100000</mu>
            <mu2>100000</mu2>
            <slip1>0</slip1>
            <slip2>0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.01"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 -0.026"/>
    </visual>
    <inertial>
      <mass value="1e-3"/>
      <inertia ixx="1e-8" iyy="1e-8" izz="1e-8" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
  
  <!-- joints -->
  <joint name="caster_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster"/>
    <origin rpy="0 0 0" xyz="${-caster_back_offset} 0 ${-chassis_height/2}"/>
  </joint>
  
  <joint name="left_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="left_wheel"/>
    <origin rpy="-1.57 0 0" xyz="${wheels_front_offset} ${chassis_width/2} ${-chassis_height/2}"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10.0" effort="1000.0"/>
    <dynamics damping="1" friction="100.0"/>
  </joint>
  
  <joint name="right_wheel_joint" type="continuous">
    <parent link="chassis"/>
    <child link="right_wheel"/>
    <origin rpy="-1.57 0 0" xyz="${wheels_front_offset} ${-chassis_width/2} ${-chassis_height/2}"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10.0" effort="1000.0"/>
    <dynamics damping="1" friction="100.0"/>
  </joint>
  
  <joint name="laser_joint" type="fixed">
    <parent link="chassis"/>
    <child link="laser_link"/>
    <origin rpy="0 0 0" xyz="${wheels_front_offset} 0 ${chassis_height/2+0.051}"/>
  </joint>
  
  <!-- transmissions -->
  <transmission name="left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
</robot>
